#--- Uninstall unnecessary applications that come with Windows out of the box ---
Write-Host "Uninstall some applications that come with Windows out of the box" -ForegroundColor "Yellow"

#Referenced to build script
# https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update
# https://github.com/jayharris/dotfiles-windows/blob/master/windows.ps1#L157
# https://gist.github.com/jessfraz/7c319b046daa101a4aaef937a20ff41f
# https://gist.github.com/alirobe/7f3b34ad89a159e6daa1
# https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/remove-default-apps.ps1

function removeApp {
    Param ([string]$appName)
    Write-Output "Trying to remove $appName"
    Get-AppxPackage $appName -AllUsers | Remove-AppxPackage
    Get-AppXProvisionedPackage -Online | Where DisplayName -like $appName | Remove-AppxProvisionedPackage -Online
}

$applicationList = @(
    "Microsoft.3DBuilder"
    "Microsoft.549981C3F5F10" # Cortana
    "Microsoft.BingFinance"
    "Microsoft.BingFoodAndDrink"
    "Microsoft.BingHealthAndFitness"
    "Microsoft.BingNews"
    "Microsoft.BingSports"
    "Microsoft.BingTranslator"
    "Microsoft.BingTravel"
    "Microsoft.BingWeather"
    "Microsoft.Messaging"
    "Microsoft.Microsoft3DViewer"
    "Microsoft.MicrosoftJournal"
    "Microsoft.MicrosoftOfficeHub"
    "*Solitaire*"
    "Microsoft.MicrosoftStickyNotes"
    "Microsoft.MixedReality.Portal"
    "Microsoft.NetworkSpeedTest"
    "Microsoft.News"
    "Microsoft.Office.OneNote"
    "Microsoft.Office.Sway"
    "Microsoft.OneConnect"
    "Microsoft.Print3D"
    "Microsoft.SkypeApp"
    "Microsoft.Todos"
    "Microsoft.WindowsAlarms"
    "Microsoft.WindowsFeedbackHub"
    "Microsoft.WindowsMaps"
    "Microsoft.WindowsSoundRecorder"
    "Microsoft.XboxApp"
    "Microsoft.ZuneVideo"
    "*.MicrosoftFamily"
    "*.QuickAssist"
    "MicrosoftTeams"
    "MSTeams"
    "ACGMediaPlayer"
    "ActiproSoftwareLLC.562882FEEB491" # Code Writer
    "*.AdobePhotoshopExpress"
    "Amazon.com.Amazon"
    "AmazonVideo.PrimeVideo"
    "Asphalt8Airborne"
    "*Autodesk*"
    "CaesarsSlotsFreeCasino"
    "COOKINGFEVER"
    "CyberLinkMediaSuiteEssentials"
    "DisneyMagicKingdoms"
    "Disney"
    "DrawboardPDF"
    "*.Duolingo-LearnLanguagesforFree"
    "*.EclipseManager"
    "*Facebook*"
    "FarmVille2CountryEscape"
    "fitbit"
    "Flipboard"
    "HiddenCity"
    "*.HULUPLUS"
    "iHeartRadio"
    "Instagram"
    "king.com*"
    "*BubbleWitch*"
    "LinkedInforWindows"
    "*MarchofEmpires*"
    "Netflix"
    "NYTCrossword"
    "OneCalendar"
    "PandoraMediaInc"
    "PhototasticCollage"
    "PicsArt-PhotoStudio"
    "*Plex*"
    "PolarrPhotoEditorAcademicEdition"
    "Royal Revolt"
    "Shazam"
    "*.LiveWallpaper"
    "SlingTV"
    "Spotify"
    "TikTok"
    "TuneInRadio"
    "Twitter"
    "Viber"
    "WinZipUniversal"
    "Wunderlist"
    "XING"
    "Microsoft.BingSearch"
    "Microsoft.GetHelp"
    "Microsoft.OneDrive"
    "Microsoft.ScreenSketch"
    "Microsoft.Windows.Photos"
    "Microsoft.WindowsPhone"
    "Microsoft.YourPhone"
    "Microsoft.ZuneMusic"
    "MicrosoftWindows.CrossDevice"
    "Microsoft.GamingApp"
    "Microsoft.OutlookForWindows"
    "Microsoft.windowscommunicationsapps"
    "Microsoft.People"
    "Microsoft.XboxGameOverlay"
    "Microsoft.XboxGamingOverlay"    
    "Microsoft.CommsPhone"
    "Microsoft.Getstarted"
    "*Minecraft*"
    "Microsoft.FreshPaint"
    "G5*"
    "*Keeper*"
);

foreach ($app in $applicationList) {
    removeApp $app
}
